//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPTest.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class AcademicPlan_Competencies
    {
        public int Id { get; set; }
        public int Id_AcademicPlan { get; set; }
        public int Id_Competencies { get; set; }
    
        public virtual AcademicPlan AcademicPlan { get; set; }
        public virtual Competencies Competencies { get; set; }
    }
}
