//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public string Type { get; set; }
        public string Name { get; set; }
        public int Hourly_Load { get; set; }
        public int Id { get; set; }
        public int Id_Chapter { get; set; }
    
        public virtual Chapter Chapter1 { get; set; }
    }
}
