//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPTest.Models
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class Discipline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discipline()
        {
            this.Discipline_Competencies = new HashSet<Discipline_Competencies>();
            this.Discipline_HourlyLoad = new HashSet<Discipline_HourlyLoad>();
            this.Knowledge = new HashSet<Knowledge>();
            this.Skills = new HashSet<Skills>();
            this.Topic = new HashSet<Topic>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Id_Kind_Of_Discipline { get; set; }
        public Nullable<int> Id_PM { get; set; }
        public int Id_Assessment_Form { get; set; }
    
        public virtual Assessment_Form Assessment_Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipline_Competencies> Discipline_Competencies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipline_HourlyLoad> Discipline_HourlyLoad { get; set; }
        public virtual Kind_Of_Discipline Kind_Of_Discipline { get; set; }
        public virtual Proffessional_Module Proffessional_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Knowledge> Knowledge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skills> Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Topic> Topic { get; set; }
    }
}
