//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literary_Source
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Literary_Source()
        {
            this.Literary_Source_Author = new HashSet<Literary_Source_Author>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Publishing_House { get; set; }
        public string Publication_Type { get; set; }
        public string URL { get; set; }
        public string City { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<System.DateTime> Date_Of_The_Application { get; set; }
        public string Access_Mode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Literary_Source_Author> Literary_Source_Author { get; set; }
    }
}
